import React, { useState, useEffect } from 'react';
import Head from 'next/head'
import { Path, NavBar, Node, About, CustButton, Work , Blog } from '../components';
import styles from "../styles/Home.module.css";
import { Inter, Roboto_Mono } from '@next/font/google'
import { Container, Button } from '@mui/material';
import work from "../utils/work.json";
import blogs from "../utils/blogs.json"
import Grid from '@mui/material/Grid';


const inter = Inter()
const robotoMono = Roboto_Mono();

export default function Home() {

  const [currProject, setCurrProject] = useState(0);

  function handleChange(value) {
    setCurrProject(value)
  }

  function handleNavChange(value)
  {
    var element = document.getElementById(value);
    element.scrollIntoView({behavior:"smooth"});
  }
  return (
    // https://sres.web.boeing.com/artifactory/api/npm/npm-releases/

    <Container>
      <Head>
        <title>Sakshi Kshatriya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.content}>
        {/* above nav bar */}
        <div className={styles.pathAboveNavBar}>
          <Path direction={"vertical"} height={"90px"} width={"0px"}></Path>
          <span className={styles.modeSwitch}></span>
          <Path direction={"vertical"} height={"50px"} width={"0px"}></Path>
        </div>
        {/* above nav bar */}

        {/* nav bar */}
        <NavBar handleChange={handleNavChange} />
        {/* nav bar */}

        {/* header */}
        <div className={`${styles.header}  ${inter.className}`}>
          <h1 className={styles.name}>Sakshi Kshatriya</h1>
          <p className={styles.jobTitle}>Full Stack Developer @Boeing</p>

          <p className={styles.aboutMe}>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Felis sit sollicitudin fusce diam eu duis nibh.
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Felis sit sollicitudin fusce diam eu duis nibh.
          </p>
        </div>
        {/* header */}

        <Button variant="outlined" className={styles.button} onClick={(e)=>window.open('../assets/Resume.pdf', '_blank')}> download my resume</Button>

        {/* path above about section */}
        <div className={styles.pathAboveNavBar}>
          <Path direction={"vertical"} height={"65px"} width={"0px"}></Path>
          <Node border={false} />
          <Path direction={"vertical"} height={"65px"} width={"0px"}></Path>
          <Node border={true} />
        </div>
        {/* path above about section */}

        {/* About section */}
        <section id="About" className={styles.aboutSection}>
          <h3 className={`${styles.sectionHeading}  ${robotoMono.className}`}>About</h3>
          <About />
        </section>
        {/* About section */}

        {/* path above work section */}
        <Path direction={"vertical"} height={"65px"} width={"0px"}></Path>
        <div className={styles.pathBelowAbout}>
          <div className={styles.horizontalPath}>
            <Path className={styles.horizontalPath} direction={"horizontal"} height={"0px"} width={"50%"}></Path>
            <Node border={false} />
            <Path className={styles.horizontalPath} direction={"horizontal"} height={"0px"} width={"50%"}></Path>
          </div>
          <Path direction={"vertical"} height={"105px"} width={"0px"}></Path>
          <Node border={true} />
        </div>
        {/* path above work section */}

        {/* Work Section */}
        <section id="Work" className={styles.workSection}>
          <div className={styles.buttons}>
            <h3 className={`${styles.sectionHeadingLeft}  ${robotoMono.className} `}>Work</h3>
            {
              work.map((project, i) => {
                return (
                  <CustButton key={i} project={project} index={i} handleChange={handleChange} currProject={currProject} />
                )
              })
            }
              <div className={styles.pathAboveNavBar}>
                <Path direction={"vertical"} height={"100px"} width={"0px"}></Path>
                <Node border={false} />
                <Path direction={"vertical"} height={"175px"} width={"0px"}></Path>
              </div>
          </div>
          <Work index={currProject} />
        </section>
        {/* Work Section */}

        {/* Path above blogs section */}
      
          <div className={styles.pathBelowWork}>
            <div className={styles.horizontalFullPath}>
              <Path  direction={"horizontal"} height={"0px"} width={"30%"}></Path>
              <Node border={false} />
              <Path  direction={"horizontal"} height={"0px"} width={"50%"}></Path>
            </div>
            <section id="Blog" className={styles.blogsSection}>
          <Grid container  className={styles.blogs}>
          {
              blogs.map((blog, i) => {
                return (
                  <Grid item md={6}>
                      < Blog key={i} blog={blog} />
                  </Grid> 
                 
                )
              })
            }
          </Grid>
            <div className={styles.vertPathAlignment}>
              <Path  direction={"vertical"} height={"105px"} width={"0px"}></Path>
              <Node border={true} />
              <h3 className={`${styles.sectionHeading}  ${robotoMono.className} `}>Blogs</h3>
              <Path  direction={"vertical"} height={"215px"} width={"0px"}></Path>
              <Node border={false} />
              <Path  direction={"vertical"} height={"395px"} width={"0px"}></Path>
            </div>
            </section>
          </div>
        {/* Path above blogs section */}

        {/* path above contact me */}
        <div className={styles.horizontalRevPath}>
              <Path  direction={"horizontal"} height={"0px"} width={"23%"}></Path>
              <Node border={false} />
              <Path  direction={"horizontal"} height={"0px"} width={"20%"}></Path>
        </div>
        <div className={styles.vertPathAlignment}>
          <Path  direction={"vertical"} height={"200px"} width={"0px"}></Path>
          <Node border={true} />
          <h3 className={`${styles.sectionHeading}  ${robotoMono.className} `}>Contact</h3>
        </div>
        {/* path above contact me */}

      </div>

      <section id="Contact"  className={`${styles.header} ${styles.contactSection} ${inter.className}`}>
        <h2 className={styles.contactSectionHeading}>Get in touch</h2>
        <p className={styles.contactSectionDescription}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
            Felis sit sollicitudin fusce diam eu duis nibh. Lorem ipsum dolor sit amet, 
            consectetur adipiscing elit. Felis sit sollicitudin fusce diam eu duis nibh.
        </p>
        <Button variant="outlined" className={styles.button}>Say hello!</Button>
      </section>

      <div className={styles.copyright}>
          Copyright 2021 | All rights reserved
      </div>
    </Container>
  )
}
