import React , {useState , useEffect} from 'react';
import Head from 'next/head'
import Path from '../components/path';
import styles from "../styles/Home.module.css";
import NavBar from "../components/navBar";
import { Inter } from '@next/font/google'

const inter = Inter()
export default function Home() {
  return (
    <div>
      <Head>
        <title>Sakshi Kshatriya</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
          {/* above nav bar */}
          <div className={styles.pathAboveNavBar}>
              <Path  direction={"vertical"} height={"90px"} width={"0px"}></Path>
              <span className={styles.modeSwitch}></span>
              <Path direction={"vertical"} height={"50px"} width={"0px"}></Path>
          </div>
           {/* above nav bar */}

           {/* nav bar */}
              <NavBar/>
           {/* nav bar */}

           {/* header */}
           <div className={`${styles.header}  ${inter.className}`}>
              <h1 className={styles.name}>Sakshi Kshatriya</h1>
              <p className={styles.jobTitle}>Full Stack Developer @Boeing</p>
           </div>
           {/* header */}
      </div>
      
    
    </div>
  )
}
